version: '3'

services:
  inbound:
    image: local/mhs-inbound:${BUILD_TAG}
    ports:
      - "${MHS_INBOUND_PORT}"
      - "${MHS_OUTBOUND_PORT}"
    environment:
      - MHS_LOG_LEVEL
      - MHS_SECRET_PARTY_KEY
      - MHS_SECRET_CLIENT_CERT
      - MHS_SECRET_CLIENT_KEY
      - MHS_SECRET_CA_CERTS
      - MHS_INBOUND_QUEUE_BROKERS=${MHS_INBOUND_QUEUE_BROKERS}
      - MHS_INBOUND_QUEUE_NAME=${MHS_INBOUND_QUEUE_NAME}
      - MHS_SECRET_INBOUND_QUEUE_USERNAME=${MHS_SECRET_INBOUND_QUEUE_USERNAME}
      - MHS_SECRET_INBOUND_QUEUE_PASSWORD=${MHS_SECRET_INBOUND_QUEUE_PASSWORD}
      - MHS_STATE_TABLE_NAME=${MHS_STATE_TABLE_NAME}
      - MHS_SYNC_ASYNC_STATE_TABLE_NAME=${MHS_SYNC_ASYNC_STATE_TABLE_NAME}
      - MHS_DB_ENDPOINT_URL=${MHS_DB_ENDPOINT_URL}
      - MHS_INBOUND_QUEUE_MESSAGE_TTL_IN_SECONDS=${MHS_INBOUND_QUEUE_MESSAGE_TTL_IN_SECONDS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MHS_INBOUND_USE_SSL=${MHS_INBOUND_USE_SSL}
      - TCP_PORTS=${MHS_INBOUND_PORT}
      - SERVICE_PORTS=${MHS_INBOUND_SERVICE_PORTS}
  outbound:
    image: local/mhs-outbound:${BUILD_TAG}
    ports:
      - ${MHS_OUTBOUND_PORT}
    environment:
      - MHS_LOG_LEVEL
      - MHS_SECRET_PARTY_KEY
      - MHS_SECRET_CLIENT_CERT
      - MHS_SECRET_CLIENT_KEY
      - MHS_SECRET_CA_CERTS
      - MHS_STATE_TABLE_NAME=${MHS_STATE_TABLE_NAME}
      - MHS_DB_ENDPOINT_URL=${MHS_DB_ENDPOINT_URL}
      - MHS_SYNC_ASYNC_STATE_TABLE_NAME=${MHS_SYNC_ASYNC_STATE_TABLE_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MHS_RESYNC_INTERVAL=${MHS_RESYNC_INTERVAL}
      - MAX_RESYNC_RETRIES=${MAX_RESYNC_RETRIES}
      - MHS_SPINE_ROUTE_LOOKUP_URL=${MHS_SPINE_ROUTE_LOOKUP_URL}
      - MHS_SPINE_ORG_CODE=${MHS_SPINE_ORG_CODE}
      - MHS_SPINE_REQUEST_MAX_SIZE=${MHS_SPINE_REQUEST_MAX_SIZE}
      - MHS_FORWARD_RELIABLE_ENDPOINT_URL=${MHS_FORWARD_RELIABLE_ENDPOINT_URL}
      - MHS_OUTBOUND_VALIDATE_CERTIFICATE=${MHS_OUTBOUND_VALIDATE_CERTIFICATE}
      - SERVICE_PORTS=${MHS_OUTBOUND_PORT}
      - MHS_OUTBOUND_ROUTING_LOOKUP_METHOD=${MHS_OUTBOUND_ROUTING_LOOKUP_METHOD}
      - MHS_SDS_API_URL=${MHS_SDS_API_URL}
      - MHS_SDS_API_KEY=${MHS_SDS_API_KEY}
      -
  route:
    image: local/mhs-route:${BUILD_TAG}
    ports:
        - "${MHS_ROUTE_PORT}:${MHS_OUTBOUND_PORT}"
    environment:
      - MHS_LOG_LEVEL
      - MHS_SDS_URL
      - MHS_SDS_SEARCH_BASE
      - MHS_DISABLE_SDS_TLS
      - MHS_SDS_REDIS_CACHE_HOST
      - MHS_SDS_REDIS_DISABLE_TLS

  mongodb:
    image: mongo
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
  rabbitmq:
    image: nhsdev/nia-rabbitmq-local:1.0.1
    ports:
      - "${RABBITMQ_PORT_1}:${RABBITMQ_PORT_1}"
      - "${RABBITMQ_PORT_2}:${RABBITMQ_PORT_2}"
    hostname: ${RABBITMQ_HOSTNAME}

  dynamodb:
    image: nhsdev/nia-dynamodb-local:1.0.3
    ports:
      - "${DYNAMODB_PORT}:${DYNAMODB_PORT}"

##we can leave it here
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

###################

